2023-06-15 11:27:53,834 INFO Inicio del scipt
2023-06-15 11:27:53,834 INFO Fin del scipt
2023-06-15 11:28:12,004 INFO Inicio del scipt
2023-06-15 11:28:12,004 ERROR Ocurriï¿½ un error
Traceback (most recent call last):
  File "C:\Users\luist\OneDrive\Escritorio\registro_log_script\Prueba1.py", line 18, in realizar_operacion
    resultado = dividir(10, 0)
                ^^^^^^^^^^^^^^
  File "C:\Users\luist\OneDrive\Escritorio\registro_log_script\Prueba1.py", line 13, in dividir
    resultado = a / b
                ~~^~~
ZeroDivisionError: division by zero
2023-06-15 11:28:12,009 INFO Fin del scipt
 